export const FETCH_SHOWS_REQUEST = 'FETCH_SHOWS_REQUEST'
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS'
export const FETCH_SHOWS_FAILURE = 'FETCH_SHOWS_FAILURE'
export const SEARCH_MOVIES = 'SEARCH_MOVIES'
export const FETCH_SHOW = 'FETCH_SHOW'

